library(stats)
library(grDevices)
library(BSDA)

dati <- read.csv("dati.csv", sep = "\t", header = TRUE)

# Statistica descrittiva
boxplot(dati$Prima, dati$Dopo)
print("------------ Prima ------------")
media_prima <- mean(dati$Prima)
print(sprintf("Media (prima): %.2f", media_prima))
mediana_prima <- median(dati$Prima)
print(sprintf("Mediana (prima): %.2f", mediana_prima))
varianza_prima <- var(dati$Prima)
print(sprintf("Varianza (prima): %.2f", varianza_prima))
deviazione_standard_prima <- sd(dati$Prima)
print(sprintf("Deviazione Standard (prima): %.2f", deviazione_standard_prima))
quantili_prima <- quantile(dati$Prima, c(0.25, 0.5, 0.75))
print("Quantili prima:")
print(sprintf(" - 25: %.2f", quantili_prima["25%"]))
print(sprintf(" - 50: %.2f", quantili_prima["50%"]))
print(sprintf(" - 75: %.2f", quantili_prima["75%"]))
outliers_prima <- boxplot.stats(dati$Prima)$out
print("Outliers prima: ")
print(outliers_prima)
print("------------ Dopo ------------")
media_dopo <- mean(dati$Dopo)
print(sprintf("Media (dopo): %.2f", media_dopo))
mediana_dopo <- median(dati$Dopo)
print(sprintf("Mediana (dopo): %.2f", mediana_dopo))
varianza_dopo <- var(dati$Dopo)
print(sprintf("Varianza (dopo): %.2f", varianza_dopo))
deviazione_standard_dopo <- sd(dati$Dopo)
print(sprintf("Deviazione Standard (dopo): %.2f", deviazione_standard_dopo))
quantili_dopo <- quantile(dati$Dopo, c(0.25, 0.5, 0.75))
print("Quantili dopo:")
print(sprintf(" - 25: %.2f", quantili_dopo["25%"]))
print(sprintf(" - 50: %.2f", quantili_dopo["50%"]))
print(sprintf(" - 75: %.2f", quantili_dopo["75%"]))
outliers_dopo <- boxplot.stats(dati$Dopo)$out
print("Outliers dopo:")
print(outliers_dopo)

# Statistica inferenziale
print(t.test(dati$Prima, dati$Dopo, paired = TRUE))

# Regressione lineare
plot(dati$Prima~dati$Dopo, data = dati)
coefficiente_di_correlazione <- cor(dati$Prima, dati$Dopo)
print(sprintf("Coefficiente di correlazione: %.2f", coefficiente_di_correlazione))
regressione_lineare <- lm(dati$Prima~dati$Dopo, data=dati)
print(regressione_lineare)
abline(coef(regressione_lineare), col = "red", lwd = 5)
coefficiente_di_determinazione <- coefficiente_di_correlazione ** 2
print(sprintf("Coefficiente di determinazione: %.2f", coefficiente_di_determinazione))
residui <- residuals(regressione_lineare)
print(residui)
plot(dati$Prima~residui, data = dati)
abline(v = 0)
print(summary(regressione_lineare))
